#!/usr/bin/env bash
cd $HOME/DRAGON
token="1805168191:AAG3kxf25R5t3z-gHvq2aL7GDyQkNZuYwq4"
while(true) do
rm -fr ../.telegram-cli
if [ ! -f ./tg ]; then
echo "≪━━━━━━𝐑𝐀𝐌𝐁𝐎━━━━━━≫"
echo "TG IS NOT FIND IN FILES BOT"
echo "≪━━━━━━𝐑𝐀𝐌𝐁𝐎━━━━━━≫"
exit 1
fi
if [ ! $token ]; then
echo "≪━━━━━━𝐑𝐀𝐌𝐁𝐎━━━━━━≫"
echo -e "\e[1;36mTOKEN IS NOT FIND IN FILE INFO.LUA \e[0m"
echo "≪━━━━━━𝐑𝐀𝐌𝐁𝐎━━━━━━≫"
exit 1
fi
echo -e "\033[38;5;208m"
echo -e "                                                  "
echo -e "\033[0;00m"
echo -e "\e[36m"
./tg -s ./DRAGON.lua -p PROFILE --bot=$token
done
